set -g status-style bg=colour233
set -ag status-style fg=colour252
setw -g mode-keys vi
set -s set-clipboard on
set -g allow-passthrough
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

unbind-key b
bind-key b last-window

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
